name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker login - Docker registry
      run: |
           echo secrets.DOCKER_USER
           echo secrets.DOCKER_PASSWORD
    
    - name: Docker login - Docker registry
      uses: docker/login-action@v2.0.0
      with:    
        username: secrets.DOCKER_USER
        password: secrets.DOCKER_PASSWORD
        
    - name: Build e Push no Azure Container Registry
      run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/subscribers-api:latest
          docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/subscribers-api:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/subscribers-api:$(date +%s)
          docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/subscribers-api
